package sync.voxel.api.runtime.item;

/**
 * Represents all possible reasons for an {@link org.bukkit.inventory.ItemStack} to be created.
 * Used for tracking item origins in crafting, smelting, trading, drops, and other mechanics.
 */
public enum VoCreateReason {

	// ===== General =====
	/**
	 * Item was created manually (e.g., via plugin code).
	 */
	CUSTOM,

	/**
	 * Source of item creation is unknown (fallback value).
	 */
	UNKNOWN,

	/**
	 * Spawned by server admins/operators.
	 */
	ADMIN_SPAWN,

	/**
	 * Generated by a plugin (non-vanilla source).
	 */
	PLUGIN_GENERATED,

	// ===== Crafting & Recipes =====
	/**
	 * Created through normal crafting in a crafting table.
	 */
	CRAFTING,

	/**
	 * Ingredient used in a crafting recipe.
	 */
	CRAFTING_INGREDIENT,

	/**
	 * Result prepared in crafting table (not yet taken).
	 */
	PREPARE_CRAFT,

	/**
	 * Created through automatic crafter block.
	 */
	CRAFTER_CRAFT,

	/**
	 * Created through stonecutter.
	 */
	STONECUTTING,

	/**
	 * Created through cartography table.
	 */
	CARTOGRAPHY,

	/**
	 * Created through loom.
	 */
	LOOM,

	// ===== Smithing =====
	/**
	 * Created through smithing table.
	 */
	SMITHING,

	/**
	 * Created by applying armor trim.
	 */
	ARMOR_TRIM,

	// ===== Furnaces & Cooking =====
	/**
	 * Created through regular furnace smelting.
	 */
	SMELTING,

	/**
	 * Created through blast furnace.
	 */
	BLASTING,

	/**
	 * Created through smoker.
	 */
	SMOKING,

	/**
	 * Cooked on a campfire.
	 */
	CAMPFIRE_COOK,

	// ===== Brewing =====
	/**
	 * Created through brewing stand (potion mixing).
	 */
	POTION_MIXING,

	// ===== Enchanting & Repair =====
	/**
	 * Enchanted at enchanting table.
	 */
	ENCHANTING,

	/**
	 * Processed through grindstone.
	 */
	GRINDSTONE,

	/**
	 * Repaired/combined at anvil.
	 */
	ANVIL,

	// ===== Trading & Bartering =====
	/**
	 * Obtained through villager/wandering trader trade.
	 */
	TRADE,

	/**
	 * Obtained through piglin bartering.
	 */
	BARTERING,

	// ===== Drops & Loot =====
	/**
	 * Dropped from breaking a block.
	 */
	BLOCK_DROP,

	/**
	 * Dropped when a block is broken by player.
	 */
	BLOCK_BREAK,

	/**
	 * Dropped from entity death.
	 */
	ENTITY_DROP,

	/**
	 * Dropped by player.
	 */
	PLAYER_DROP,

	/**
	 * Music disc dropped from creeper killed by skeleton.
	 */
	RECORD_DROP,

	/**
	 * Found through fishing.
	 */
	FISHING,

	/**
	 * Found in loot chest/container.
	 */
	LOOT_CHEST,

	/**
	 * Generated from loot table.
	 */
	LOOT_TABLE,

	/**
	 * Found through archaeology (suspicious blocks).
	 */
	ARCHAEOLOGY,

	/**
	 * Spawned as item entity in world.
	 */
	ITEM_SPAWN,

	/**
	 * Dropped from trial spawner.
	 */
	TRIAL_SPAWNER,

	/**
	 * Trial key obtained from trial chamber.
	 */
	TRIAL_KEY,

	/**
	 * Goat horn obtained from ramming goat.
	 */
	GOAT_HORN,

	// ===== Inventory Management =====
	/**
	 * Item picked up from ground.
	 */
	PICKUP,

	/**
	 * Item moved via inventory drag.
	 */
	INVENTORY_DRAG,

	/**
	 * Item moved via hotbar swap.
	 */
	HOTBAR_SWAP,

	/**
	 * Stack split (right-click).
	 */
	STACK_SPLIT,

	/**
	 * General inventory item movement.
	 */
	INVENTORY_MOVE,

	/**
	 * Item held in cursor.
	 */
	CURSOR_ITEM,

	// ===== Creative & Commands =====
	/**
	 * Given through creative mode.
	 */
	CREATIVE_GIVE,

	/**
	 * Given through command (e.g., /give).
	 */
	COMMAND,

	// ===== Player Events =====
	/**
	 * Item in inventory when player joins server.
	 */
	PLAYER_JOIN,

	/**
	 * Item obtained on player respawn.
	 */
	PLAYER_RESPAWN,

	// ===== Interactions =====
	/**
	 * Item used in entity interaction.
	 */
	ENTITY_INTERACT,

	// ===== Special Items =====
	/**
	 * Bucket filled with liquid.
	 */
	BUCKET_FILL,

	/**
	 * Bucket emptied of liquid.
	 */
	BUCKET_EMPTY,

	/**
	 * Item obtained through shearing entity.
	 */
	SHEARING,

	// ===== World Generation =====
	/**
	 * Item generated during world/chunk generation.
	 */
	WORLD_GENERATION,

	/**
	 * Item found in naturally generated structure.
	 */
	STRUCTURE_LOOT,

	// ===== Breeding & Animals =====
	/**
	 * Item obtained from breeding animals.
	 */
	BREEDING,

	/**
	 * Item obtained from milking cow/mushroom.
	 */
	MILKING,

	/**
	 * Egg laid by chicken.
	 */
	EGG_LAY,

	/**
	 * Wool obtained from sheep (natural shedding).
	 */
	WOOL_SHED,

	// ===== Farming =====
	/**
	 * Crop harvested from farmland.
	 */
	CROP_HARVEST,

	/**
	 * Item obtained from composting.
	 */
	COMPOSTING,

	/**
	 * Bone meal applied to plants.
	 */
	BONE_MEAL_GROWTH,

	// ===== Redstone & Mechanisms =====
	/**
	 * Item dispensed from dispenser.
	 */
	DISPENSER,

	/**
	 * Item dropped from dropper.
	 */
	DROPPER,

	/**
	 * Item moved by hopper.
	 */
	HOPPER_TRANSFER,

	// ===== Combat =====
	/**
	 * Item obtained through combat/PvP.
	 */
	COMBAT_DROP,

	/**
	 * Arrow shot from bow/crossbow.
	 */
	PROJECTILE_SHOT,

	// ===== Multiplayer =====
	/**
	 * Item shared between players.
	 */
	PLAYER_TRADE,

	/**
	 * Item duplicated (typically should be prevented).
	 */
	DUPLICATION,

	// ===== Events & Seasonal =====
	/**
	 * Item obtained during special event.
	 */
	EVENT_REWARD,

	/**
	 * Daily/periodic reward item.
	 */
	PERIODIC_REWARD,

	// ===== Data/Save =====
	/**
	 * Item loaded from player data/save file.
	 */
	DATA_LOAD,

	/**
	 * Item restored from backup.
	 */
	BACKUP_RESTORE
}